# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-11 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('data', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estoque', models.ManyToManyField(to='intmed.Item')),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='produtos',
            field=models.ManyToManyField(to='intmed.Item'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intmed.Mercado'),
        ),
    ]
