# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intmed', '0002_item_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
