# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-13 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intmed', '0003_entrega_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercado',
            name='estoque',
            field=models.ManyToManyField(null=True, to='intmed.Item'),
        ),
    ]
